### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ld-xy** [pbehjatii/FENet#3] opened 2022-11-05 14:02 UTC
Why does this model run out of memory after running several consecutive pictures？I hope it can be answered, thank you

**Comment by pbehjatii** [comment] 2022-11-05 14:08
Which dataset are using?

**Comment by pbehjatii** [comment] 2022-11-05 14:10
Anyway, if the model runs out of memory, you need to change the dataset name to the name of your dataset in line 37 in sample.py. In this way, you are not feeding the whole image to the network. It means that we are dividing the main image into small pieces and feeding them to the network. And finally, Finally, we concatenate the images to have the full image again. Please let me know if the problem is solved.

**Comment by ld-xy** [comment] 2022-11-05 14:10
> 

It uses a data set built by itself, with a size of 320x180x3

**Comment by ld-xy** [comment] 2022-11-05 14:16
> Anyway, if the model runs out of memory, you need to change the dataset name to the name of your dataset in line 37 in sample.py. In this way, you are not feeding the whole image to the network.

think you！！！but Why do 320x180 small images also report? Is it because the memory consumption in the model is large?

**Comment by pbehjatii** [comment] 2022-11-05 14:21
The memory consumption is not large. But I don't know why you have this problem. Because I only had a problem generating images of the Urban100 dataset which has big images.

**Comment by pbehjatii** [comment] 2022-11-05 14:23
Also please keep in mind that you are feeding the network images with the size of 320*180 and you are enhancing the image 4 times bigger.

**Comment by ld-xy** [comment] 2022-11-05 14:24
> The memory consumption is not large. But I don't know why you have this problem. Because I only had a problem generating images of the Urban100 dataset which has big images.

okok，Thank you very much for answering my questions

**Comment by pbehjatii** [comment] 2022-11-05 14:25
Since the problem is solved, I am closing this issue.

**Comment by ld-xy** [comment] 2022-11-05 14:25
> Since the problem is solved, I am closing this issue.

**Closed as completed by pbehjatii** 2022-11-05 14:25 UTC
